"""create all tables

Revision ID: 3c80cd123246
Revises: 
Create Date: 2022-11-23 16:02:31.880060

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '3c80cd123246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE activities SET SCHEMA {SCHEMA};")

    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE amenities SET SCHEMA {SCHEMA};")

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

    op.create_table('campgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('sites', sa.Integer(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('min_nights', sa.Integer(), nullable=False),
    sa.Column('max_nights', sa.Integer(), nullable=False),
    sa.Column('checkin_time', sa.String(), nullable=False),
    sa.Column('checkout_time', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE campgrounds SET SCHEMA {SCHEMA};")

    op.create_table('campgroundimages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campground_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('preview', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campground_id'], ['campgrounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE campgroundimages SET SCHEMA {SCHEMA};")

    op.create_table('campground_activities',
    sa.Column('campgroundId', sa.Integer(), nullable=True),
    sa.Column('activityId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activityId'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['campgroundId'], ['campgrounds.id'], )
    )
    if environment == "production":
        op.execute(f"ALTER TABLE campground_activities SET SCHEMA {SCHEMA};")

    op.create_table('campground_amenities',
    sa.Column('campgroundId', sa.Integer(), nullable=True),
    sa.Column('amenityId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amenityId'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['campgroundId'], ['campgrounds.id'], )
    )
    if environment == "production":
        op.execute(f"ALTER TABLE campground_amenities SET SCHEMA {SCHEMA};")

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('campground_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campground_id'], ['campgrounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE reviews SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('campground_amenities')
    op.drop_table('campground_activities')
    op.drop_table('campgroundimages')
    op.drop_table('campgrounds')
    op.drop_table('users')
    op.drop_table('amenities')
    op.drop_table('activities')
    # ### end Alembic commands ###
