"""create all tables

Revision ID: 4cfddd1db033
Revises: 
Create Date: 2022-11-23 14:45:08.575982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfddd1db033'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('acres', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('min_nights', sa.Integer(), nullable=False),
    sa.Column('max_nights', sa.Integer(), nullable=False),
    sa.Column('checkin_time', sa.String(), nullable=False),
    sa.Column('checkout_time', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campgroundImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campground_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('preview', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campground_id'], ['campgrounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campground_activities',
    sa.Column('campgroundId', sa.Integer(), nullable=True),
    sa.Column('activityId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activityId'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['campgroundId'], ['campgrounds.id'], )
    )
    op.create_table('campground_amenities',
    sa.Column('campgroundId', sa.Integer(), nullable=True),
    sa.Column('amenityId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amenityId'], ['amenities.id'], ),
    sa.ForeignKeyConstraint(['campgroundId'], ['campgrounds.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campground_amenities')
    op.drop_table('campground_activities')
    op.drop_table('campgroundImages')
    op.drop_table('campgrounds')
    op.drop_table('users')
    op.drop_table('amenities')
    op.drop_table('activities')
    # ### end Alembic commands ###
